spring:
  profiles:
    active: DEV
  application:
    name: ruota

security:
  admin:
    password: ${ADMIN_PASSWORD}

jwt:
  secret: 0349dffb83027c2e2ba5b1cdf14bd63c5bdf9f809466c056999cfb754bf4092b
  expiration: 86400000 # 24 ore in millisecondi
  #expiration:  60000 #1 minuto in millisecondi


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

swagger:
  server:
    url: ${SWAGGER_SERVER_URL:http://localhost:8083/api/ruota}

server:
  servlet:
    context-path: /api/ruota
  port: ${PORT:8083}
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEYSTORE:classpath:ruota-keystore.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:changeit}
    key-store-type: PKCS12
    key-alias: ruota
logging:
  level:
    org:
      hibernate:
        SQL: ${SHOW_SQL:INFO}
        orm:
          jdbc:
            bind: ${SHOW_SQL_PARAMETER:INFO}
